# setting env to production will minify the html
env: production
#env: dev

exclude: ['Gruntfile.js', 'package.json', 'readme.md', 'sftpCache.json', 'node_modules', 'armydotmil.github.io']

gems:
  - octopress-minify-html
  - octopress-autoprefixer

sass:
  sass_dir: _scss
  style: compressed

title: Army Public Affairs

url: http://www.army.mil/info/institution/publicAffairs/
