version: 0.2

phases:
  install:
    commands:
        - locale-gen en_US en_US.UTF-8
        - dpkg-reconfigure locales
        - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
        - apt-get install -y nodejs
        - gem install bundler
        - bundle install
        - npm install
        - npm install -g grunt-cli
  build:
    commands:
        - echo "******** CHANGE BRANCH ********"
        - git checkout $GIT_BRANCH
        - echo "******** UPDATE SUBMODULE ********"
        - git submodule init
        - git submodule update
        - echo "******** Run Grunt Task ********"
        - grunt sass
        - grunt browserify
        - grunt uglify
        - echo "******** Building Jekyll site ********"
        - export LC_ALL=en_US.UTF-8
        - export LC_TYPE=en_US.UTF-8
        - export LANGUAGE=en_US.UTF-8
        - export LANG=en_US.UTF-8
        - jekyll build -t
        - echo "******** Uploading to S3 ********"
        - aws s3 sync _site/ s3://$S3_BUCKET/publicaffairs --exclude "e2/*"
        - aws s3 sync _site/e2/js/rv7/publicaffairs s3://$S3_BUCKET/e2/js/rv7/publicaffairs
        - aws s3 sync _site/e2/css/rv7/publicaffairs s3://$S3_BUCKET/e2/css/rv7/publicaffairs
